INSERT ALL
 INTO USERS VALUES('1','admin','admin','admin@morahaji.com','admin','ext','','1')
 INTO USERS VALUES('2','TooColdWinter','ºê¸®Æ®´Ï Á¡·Ê','britntney@google.com','!important','10','','1')
 INTO USERS VALUES('3','SantaCross','º°ºû·Î±á','starlight@naver.com','toggledata','20','','1')
 INTO USERS VALUES('4','ModalHater','°ûµÎÆÈ','modalmodal@hanmail.net','lime&&33','30','','1')
 INTO USERS VALUES('5','BBangBBang','ÀÌÀç¿ë','samsunglover@hotmail.net','808@@@','40','','1')
 INTO USERS VALUES('6','JavaLover','ÀÌ°ÇÈñ','jjangjjang789@empas.com','Samsung*','50','','1')
 INTO USERS VALUES('7','Reasonable88','±Í¿°µÕÀÌ','prettywomen@hitel.net','twinkle55','60','','1')
 INTO USERS VALUES('8','OrakGrak','»ÑÀ×»ÑÀ×','jeongsintong1@netian.com','$fgas&*','10','','1')
 INTO USERS VALUES('9','Developer135','ÄÁÆ®·Ñ£p','ctrlz135@nate.com','!@#$%^&','20','','1')
 INTO USERS VALUES('10','EclipseJJang','±èÀ¯¹Ì','yumi309@hanmir.com','1@3$5^7','30','','1')
 INTO USERS VALUES('11','DBdb5678','¹Ú¸··Ê','yurajjang12@dreamwiz.com','parkinterpark','40','','1')
 INTO USERS VALUES('12','Hammer5880','¿ìÈý¿ìÈý','azummayeogi@korea.com','dngltdnglt','50','','1')
 INTO USERS VALUES('13','Elsa','ºü´ãºü´ã','letitgoletitgo@nate.com','skxmfkddmfhrkwk','60','','1')
 INTO USERS VALUES('14','Olarph','³ªÆ®¶û','doyouwanna@buildasnow.man','%&(xlvksl','40','','1')
 INTO USERS VALUES('15','OhFrozen77','Æ¼ÆÄ´Ï','breakfast@tiffany.lov','mamamomo','40','','1')
 INTO USERS VALUES('16','CountryRock','³ª´Â¾ß¶ô½ºÅ¸','rockandroll@nate.com','rongrong22','10','','1')
 INTO USERS VALUES('17','TaylerSwift','Å×ÀÏ·¯','36ruralliving@hitel.net','popoqwqw','20','','1')
 INTO USERS VALUES('18','bestdriver','º£½ºÆ®µå·¹¼­','bestdriver123@dreamwiz.com','almond^^','30','','1')
 INTO USERS VALUES('19','LoveandHate','ÀÌÁß¼¼³ú','maxminminus@kebi.com','brainwasher','40','','1')
 INTO USERS VALUES('20','Sunrise','ÇØµ¸ÀÌ','sunandmoon28@hanmail.net','goehedl','50','','1')
 SELECT *  FROM DUAL;